name: global-inflation-analysis
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - jupyter
  - joblib
